const challenges = [
    "Take a 30-second cold shower.",
    "Do 20 push-ups.",
    "Meditate for 10 minutes.",
    "Write down 3 things you're grateful for.",
    "3 things you have messed up today.",
    "Go up to a stranger and give him/her a compliment.",
    "No electronics for an hour."
    "Spend the rest of the day with no music, podcasts and media."
    "Wake up at 4am and finish your chores before the day starts."
    "Not a single complaint allowed, no matter what happens."
    "If something needs to be done, do it immediately without hesitation."
    "100 word essay, where you are know and where you want to end up."
    "Do not speak unless absolutely necessary."
    "Express all your deepest frustrations in a letter and then burn the it."
    "Sit in public without your phone - just observe the world without distractions."
    "Go the whole day without coffee, nicotine or any stimulants."
    "Choose a bad habit and cut it cold turkey today."
    "Read 50 pages - no skipping, no distractions, just deep reading."
    "Doesn't matter what the weather is - go outside and run a 5k."
    "Walk a mile with a weighted backpack (50+ lbs)."
    "Write Your Own Eulogy – Reflect on what you want your legacy to be. 100 words minimum."
    "Postpone something pleasurable until tomorrow, even if you’ve earned it."
    "Write down 5 of THE most important goals you have for the next 5 years."
    "Speak only in a calm, neutral voice all day, no matter what happens."
    "Drink at least 3 liters of water today, no other beverages allowed."
    "Give up something you love for a week – coffee, gaming, sugar, social media—pick one and quit for 7 days."
    "30 seconds cold shower first thing in the morning."
    "Delete an app – get rid of one distracting app permanently."
    "Let someone else take your place in line, on a seat, or in traffic."
    "Make eye contact and say hello to 5 strangers you pass."
    "Decline something today without justifying yourself."
    "Don’t break eye contact first in any conversation."
    "Train in complete silence, no music, no headphones, no talking."
    "Maintain perfect posture all day—no slouching, no leaning."
    "Only breath through your nose the entire day."
    "Park your car or bike at the furthest distance possible."
    "No coffee, no energy drinks, no sugar—rely only on your natural energy."
    "Make a 100 word plan preparing for a future hardship (e.g., job loss, emergency)."
    "Blame no one for anything. Own every aspect of your life today."
    "Approach every challenge today as if the universe is testing you."
    "Eat only one meal today, and it must be completely plain."
    "Plan every hour of your day and stick to it 100%."
    "Turn off wifi and bluetooth, only use the phone wen asnwering a call."
    "No sitting while eating, no matter how long it takes."
    "Do not watch or listen to anyting while eating."
    "Avoid elevators and escalators for an entire day, no matter how many floors."
    "Pick one thing and don’t stop until it’s 100% finished. No switching."
    "Break a Rule (Without Getting Caught) – Challenge your fear of authority (ethically)."
    "Brush your teeth, write, and eat with your non-dominant hand all day."
    "Train your brain by memorizing a 20 digit number sequence."
    "Minimum of 200 words essay on What has made you, you."
    "Walk in the rain without an umbrella – accept discomfort and keep moving forward."
    "Only speak if it adds value or is truly needed."
    "No “I” or “Me” challenge – avoid referring to yourself all day."
    "Do not correct anyone – even if they’re wrong, let them be wrong."
    "Listen without interrupting – no speaking until the other person fully finishes their thought."
    "Sit in a noisy place and meditate – find calm in chaos by focusing only on your breath."
    "Every time you want something (food, scrolling, resting), delay it 10 minutes first."
    "Walk 10,000 steps before breakfast – earn your first meal with physical effort."
    "No repeating yourself – say things once, clearly, and then let them stand."
    "Speak more slowly than normal – train deliberate, controlled communication."
    "Hold a conversation without saying ‘Um’ or ‘Like’ – speak with clarity and power."
    "Fast for 24 ours - only water, tea and black coffee."
    "Wake up at 4 AM - no snooze, no complaining."
    "Do a cold shower at the middle of a day."
    "Write a 150 word essay on Your Own Weaknesses."
    "Spend the entire day without looking in a mirror."
    "Journal your entire day at the evening."
    "Only use cash for a week – no digital payments, just real money."
    "Meditate for 20 minutes."
    "Give away something you own."
    "Do a good deed anonymously – no recognition."
    "No processed foods for a week."
    "Wear the same outfit for 3 days."
    "Let people talk over you without reacting – kill the need for validation."
    "Be completely honest for a week – no white lies."
    "Live like you’re broke for a week – no luxuries."
    "Write a letter to someone and never send it."
    "Do 10 000 steps every day for the next week."
    "Do not talk somebody behind their back for the next week."
    "Ask a stranger how his/her's day has been."
];

document.getElementById("challengeButton").addEventListener("click", function() {
    const randomIndex = Math.floor(Math.random() * challenges.length);
    document.getElementById("challengeText").innerText = challenges[randomIndex];
});
